require('lazy').setup({
  'tpope/vim-sleuth',
  require 'ori/plugins/core',
  require 'ori/plugins/gitsigns',
  require 'ori/plugins/which-key',
  require 'ori/plugins/telescope',
  require 'ori/plugins/lspconfig',
  require 'ori/plugins/conform',
  require 'ori/plugins/cmp',
  require 'ori/plugins/colorscheme',
  require 'ori/plugins/todo-comments',
  require 'ori/plugins/mini',
  require 'ori/plugins/treesitter',
  require 'ori/plugins/hop',
  require 'ori/plugins/avante',
  require 'ori/plugins/copilot',
  require 'ori/plugins/alpha',
  require 'ori/plugins/commenter',
  require 'ori/plugins/debug',
  require 'ori/plugins/harpoon',
  require 'ori/plugins/git-dev',
  require 'ori/plugins/ufo',
}, {})
